version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./logs/energy_forecast.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: ./logs/energy_forecast_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  "":  # root logger
    level: INFO
    handlers: [console, file_handler, error_file_handler]
    propagate: true

  data_loader:
    level: INFO
    handlers: [console, file_handler]
    propagate: false

  preprocessing:
    level: INFO
    handlers: [console, file_handler]
    propagate: false

  models:
    level: INFO
    handlers: [console, file_handler]
    propagate: false

  api:
    level: INFO
    handlers: [console, file_handler]
    propagate: false

  visualization:
    level: INFO
    handlers: [console, file_handler]
    propagate: false